### ISSUE TITLE
MapInfos optimization available using "keyasint" struct tag

### ISSUE THREAD

**Issue by x448** [akhenakh/insideout#4]
@akhenakh hi!  I noticed you're using fxamacker/cbor.  It has `keyasint` struct tag which can make structs like MapInfos more compact.

The `keyasint` struct tag makes struct fields with nice names automatically translate to CBOR map with specified integer keys.

Also, `keyasint` is about 26% faster in fxamacker/cbor 2.2 compared to 1.x.  

I hope you find this useful.

![alt text](https://github.com/fxamacker/images/raw/master/cbor/v2.2.0/cbor_struct_tags_api.svg?sanitize=1 "CBOR API and Go Struct Tags")

**Comment by akhenakh** [comment]
You are fast !I made it public a few hours ago :)

Thanks for the tips I’ll look into it.

**Comment by akhenakh** [comment]
updated to v2 and use keyasint, thank you
